module.exports = {
  env: {
    node: true,
  },
  plugins: ["@typescript-eslint", "node", "prettier"],
  rules: {
    "prettier/prettier": [
      "error",
      {
        printWidth: 120,
        trailingComma: "all",
        singleQuote: false,
        endOfLine: "auto",
      },
    ],
    "no-console": [
      "warn",
      {
        allow: ["warn", "error"],
      },
    ],
    "no-debugger": ["error"],
    "node/global-require": ["warn"],
    "node/no-deprecated-api": ["error"],
    "@typescript-eslint/ban-ts-comment": [
      "error",
      {
        "ts-ignore": "allow-with-description",
        minimumDescriptionLength: 20,
      },
    ],
    "@typescript-eslint/naming-convention": [
      "warn",
      {
        selector: ["variable"],
        format: ["camelCase", "UPPER_CASE"],
      },
      {
        selector: "parameter",
        format: ["camelCase"],
      },
      {
        selector: "memberLike",
        modifiers: ["private"],
        format: ["camelCase"],
        leadingUnderscore: "forbid",
        trailingUnderscore: "forbid",
      },
      {
        selector: ["enumMember"],
        format: ["UPPER_CASE"],
      },
      {
        selector: "property",
        format: ["camelCase"],
        filter: {
          regex: "\\d+",
          match: false,
        },
      },
      {
        selector: "typeLike",
        format: ["PascalCase"],
      },
      {
        selector: "variable",
        modifiers: ["destructured"],
        format: null,
      },
    ],
    "@typescript-eslint/ban-types": ["error"],
    "no-array-constructor": ["off"],
    "@typescript-eslint/no-array-constructor": ["error"],
    "@typescript-eslint/no-duplicate-enum-values": ["error"],
    "@typescript-eslint/no-explicit-any": ["error"],
    "@typescript-eslint/no-extra-non-null-assertion": ["error"],
    "no-loss-of-precision": ["off"],
    "@typescript-eslint/no-loss-of-precision": ["error"],
    "@typescript-eslint/no-misused-new": ["error"],
    "@typescript-eslint/no-namespace": ["error"],
    "@typescript-eslint/no-non-null-asserted-optional-chain": ["error"],
    "@typescript-eslint/no-this-alias": ["error"],
    "@typescript-eslint/no-unnecessary-type-constraint": ["error"],
    "@typescript-eslint/no-unsafe-declaration-merging": ["error"],
    "no-unused-vars": [
      "off",
      {
        args: "none",
      },
    ],
    "@typescript-eslint/no-unused-vars": ["error"],
    "@typescript-eslint/no-var-requires": ["error"],
    "@typescript-eslint/prefer-as-const": ["error"],
    "@typescript-eslint/triple-slash-reference": ["error"],
    "for-direction": ["error"],
    "getter-return": ["warn"],
    "no-cond-assign": ["warn", "except-parens"],
    "no-constant-condition": [
      "warn",
      {
        checkLoops: false,
      },
    ],
    "no-dupe-args": ["error"],
    "no-dupe-keys": ["warn"],
    "no-duplicate-case": ["warn"],
    "no-empty": [
      "warn",
      {
        allowEmptyCatch: true,
      },
    ],
    "no-empty-character-class": ["warn"],
    "no-invalid-regexp": ["error"],
    "no-obj-calls": ["error"],
    "no-unreachable": ["warn"],
    "valid-typeof": [
      "warn",
      {
        requireStringLiterals: false,
      },
    ],
    "no-caller": ["error"],
    "no-extra-label": ["warn"],
    "no-global-assign": ["warn"],
    "no-octal": ["error"],
    "no-octal-escape": ["error"],
    "no-self-assign": ["warn"],
    "no-unmodified-loop-condition": ["warn"],
    "no-unused-expressions": [
      "warn",
      {
        allowShortCircuit: true,
        allowTernary: true,
        allowTaggedTemplates: true,
        enforceForJSX: false,
      },
    ],
    "no-unused-labels": ["warn"],
    "no-with": ["error"],
    "no-delete-var": ["error"],
    "no-undef": ["error"],
    "constructor-super": ["error"],
    "no-const-assign": ["error"],
    "no-dupe-class-members": ["warn"],
    "no-new-symbol": ["error"],
    "no-this-before-super": ["error"],
    "no-useless-constructor": ["warn"],
    "arrow-body-style": ["off"],
    "prefer-arrow-callback": ["off"],
    curly: [0],
    "lines-around-comment": [0],
    "max-len": [0],
    "no-confusing-arrow": [0],
    "no-mixed-operators": [0],
    "no-tabs": [0],
    "no-unexpected-multiline": [0],
    quotes: [0],
    "@typescript-eslint/lines-around-comment": [0],
    "@typescript-eslint/quotes": [0],
    "babel/quotes": [0],
    "vue/html-self-closing": [0],
    "vue/max-len": [0],
    "array-bracket-newline": ["off"],
    "array-bracket-spacing": ["off"],
    "array-element-newline": ["off"],
    "arrow-parens": ["off"],
    "arrow-spacing": ["off"],
    "block-spacing": ["off"],
    "brace-style": ["off"],
    "comma-dangle": ["off"],
    "comma-spacing": ["off"],
    "comma-style": ["off"],
    "computed-property-spacing": ["off"],
    "dot-location": ["off"],
    "eol-last": ["off"],
    "func-call-spacing": ["off"],
    "function-call-argument-newline": ["off"],
    "function-paren-newline": ["off"],
    "generator-star-spacing": ["off"],
    "implicit-arrow-linebreak": ["off"],
    indent: ["off"],
    "jsx-quotes": ["off"],
    "key-spacing": ["off"],
    "keyword-spacing": ["off"],
    "linebreak-style": ["off"],
    "max-statements-per-line": ["off"],
    "multiline-ternary": ["off"],
    "newline-per-chained-call": ["off"],
    "new-parens": ["off"],
    "no-extra-parens": ["off"],
    "no-extra-semi": ["off"],
    "no-floating-decimal": ["off"],
    "no-mixed-spaces-and-tabs": ["off"],
    "no-multi-spaces": ["off"],
    "no-multiple-empty-lines": ["off"],
    "no-trailing-spaces": ["off"],
    "no-whitespace-before-property": ["off"],
    "nonblock-statement-body-position": ["off"],
    "object-curly-newline": ["off"],
    "object-curly-spacing": ["off"],
    "object-property-newline": ["off"],
    "one-var-declaration-per-line": ["off"],
    "operator-linebreak": ["off"],
    "padded-blocks": ["off"],
    "quote-props": ["off"],
    "rest-spread-spacing": ["off"],
    semi: ["off"],
    "semi-spacing": ["off"],
    "semi-style": ["off"],
    "space-before-blocks": ["off"],
    "space-before-function-paren": ["off"],
    "space-in-parens": ["off"],
    "space-infix-ops": ["off"],
    "space-unary-ops": ["off"],
    "switch-colon-spacing": ["off"],
    "template-curly-spacing": ["off"],
    "template-tag-spacing": ["off"],
    "unicode-bom": ["off"],
    "wrap-iife": ["off"],
    "wrap-regex": ["off"],
    "yield-star-spacing": ["off"],
    "@babel/object-curly-spacing": ["off"],
    "@babel/semi": ["off"],
    "@typescript-eslint/block-spacing": ["off"],
    "@typescript-eslint/brace-style": ["off"],
    "@typescript-eslint/comma-dangle": ["off"],
    "@typescript-eslint/comma-spacing": ["off"],
    "@typescript-eslint/func-call-spacing": ["off"],
    "@typescript-eslint/indent": ["off"],
    "@typescript-eslint/key-spacing": ["off"],
    "@typescript-eslint/keyword-spacing": ["off"],
    "@typescript-eslint/member-delimiter-style": ["off"],
    "@typescript-eslint/no-extra-parens": ["off"],
    "@typescript-eslint/no-extra-semi": ["off"],
    "@typescript-eslint/object-curly-spacing": ["off"],
    "@typescript-eslint/semi": ["off"],
    "@typescript-eslint/space-before-blocks": ["off"],
    "@typescript-eslint/space-before-function-paren": ["off"],
    "@typescript-eslint/space-infix-ops": ["off"],
    "@typescript-eslint/type-annotation-spacing": ["off"],
    "babel/object-curly-spacing": ["off"],
    "babel/semi": ["off"],
    "flowtype/boolean-style": ["off"],
    "flowtype/delimiter-dangle": ["off"],
    "flowtype/generic-spacing": ["off"],
    "flowtype/object-type-curly-spacing": ["off"],
    "flowtype/object-type-delimiter": ["off"],
    "flowtype/quotes": ["off"],
    "flowtype/semi": ["off"],
    "flowtype/space-after-type-colon": ["off"],
    "flowtype/space-before-generic-bracket": ["off"],
    "flowtype/space-before-type-colon": ["off"],
    "flowtype/union-intersection-spacing": ["off"],
    "react/jsx-child-element-spacing": ["off"],
    "react/jsx-closing-bracket-location": ["off"],
    "react/jsx-closing-tag-location": ["off"],
    "react/jsx-curly-newline": ["off"],
    "react/jsx-curly-spacing": ["off"],
    "react/jsx-equals-spacing": ["off"],
    "react/jsx-first-prop-new-line": ["off"],
    "react/jsx-indent": ["off"],
    "react/jsx-indent-props": ["off"],
    "react/jsx-max-props-per-line": ["off"],
    "react/jsx-newline": ["off"],
    "react/jsx-one-expression-per-line": ["off"],
    "react/jsx-props-no-multi-spaces": ["off"],
    "react/jsx-tag-spacing": ["off"],
    "react/jsx-wrap-multilines": ["off"],
    "standard/array-bracket-even-spacing": ["off"],
    "standard/computed-property-even-spacing": ["off"],
    "standard/object-curly-even-spacing": ["off"],
    "unicorn/empty-brace-spaces": ["off"],
    "unicorn/no-nested-ternary": ["off"],
    "unicorn/number-literal-case": ["off"],
    "vue/array-bracket-newline": ["off"],
    "vue/array-bracket-spacing": ["off"],
    "vue/array-element-newline": ["off"],
    "vue/arrow-spacing": ["off"],
    "vue/block-spacing": ["off"],
    "vue/block-tag-newline": ["off"],
    "vue/brace-style": ["off"],
    "vue/comma-dangle": ["off"],
    "vue/comma-spacing": ["off"],
    "vue/comma-style": ["off"],
    "vue/dot-location": ["off"],
    "vue/func-call-spacing": ["off"],
    "vue/html-closing-bracket-newline": ["off"],
    "vue/html-closing-bracket-spacing": ["off"],
    "vue/html-end-tags": ["off"],
    "vue/html-indent": ["off"],
    "vue/html-quotes": ["off"],
    "vue/key-spacing": ["off"],
    "vue/keyword-spacing": ["off"],
    "vue/max-attributes-per-line": ["off"],
    "vue/multiline-html-element-content-newline": ["off"],
    "vue/multiline-ternary": ["off"],
    "vue/mustache-interpolation-spacing": ["off"],
    "vue/no-extra-parens": ["off"],
    "vue/no-multi-spaces": ["off"],
    "vue/no-spaces-around-equal-signs-in-attribute": ["off"],
    "vue/object-curly-newline": ["off"],
    "vue/object-curly-spacing": ["off"],
    "vue/object-property-newline": ["off"],
    "vue/operator-linebreak": ["off"],
    "vue/quote-props": ["off"],
    "vue/script-indent": ["off"],
    "vue/singleline-html-element-content-newline": ["off"],
    "vue/space-in-parens": ["off"],
    "vue/space-infix-ops": ["off"],
    "vue/space-unary-ops": ["off"],
    "vue/template-curly-spacing": ["off"],
    "generator-star": ["off"],
    "indent-legacy": ["off"],
    "no-arrow-condition": ["off"],
    "no-comma-dangle": ["off"],
    "no-reserved-keys": ["off"],
    "no-space-before-semi": ["off"],
    "no-spaced-func": ["off"],
    "no-wrap-func": ["off"],
    "space-after-function-name": ["off"],
    "space-after-keywords": ["off"],
    "space-before-function-parentheses": ["off"],
    "space-before-keywords": ["off"],
    "space-in-brackets": ["off"],
    "space-return-throw-case": ["off"],
    "space-unary-word-ops": ["off"],
    "react/jsx-space-before-closing": ["off"],
  },
  settings: {
    jest: {
      version: "detect",
    },
  },
  overrides: [
    {
      files: ["*.ts", "*.tsx", "*.mts", "*.cts"],
      rules: {
        "constructor-super": "off",
        "getter-return": "off",
        "no-const-assign": "off",
        "no-dupe-args": "off",
        "no-dupe-class-members": "off",
        "no-dupe-keys": "off",
        "no-func-assign": "off",
        "no-import-assign": "off",
        "no-new-symbol": "off",
        "no-obj-calls": "off",
        "no-redeclare": "off",
        "no-setter-return": "off",
        "no-this-before-super": "off",
        "no-undef": "off",
        "no-unreachable": "off",
        "no-unsafe-negation": "off",
        "no-var": "error",
        "prefer-const": "error",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
        "valid-typeof": "off",
      },
    },
  ],
};
