app:
  environment: development

endpoints:
  default: https://api-dev.example.com/api

features:
  msw: false
  debugMode: true
  analytics: false
  betaFeatures: true

analytics:
  measurementId: ""
